import Head from 'next/head'
import ThemeToggle from '../modules/index/ThemeToggle'
import { SlicedButton, Text } from '../components/ThemedElements';
import TextLabel from '@/components/TextLabel';
import { styled } from 'stitches.config';
import Image from 'next/image'
import BorderContainer from '@/components/BorderContainer';

export default function Home() {
  return (
    <>
      <Head>
        <title>x7ci - index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Wrapper>
          <NavigationBar>
            <div style={{ width: 0 }} />
            <Image
              src="/react_hexagon.png"
              alt="Picture of the author"
              width={38}
              height={40}
            />
            <NavbarTitleContainer>
              <Text color="yellow" size={6} weight={2}>
                {'FULL STACK '}
                <Text size={6} weight={1} >DEVELOPER</Text>
              </Text>
              <Text color="cyan" size={1} weight={2}>
                {'SEQUENCE: '}
                <Text color="cyanLight" size={1} weight={2}>
                  {'771-C/3309-M2'}
                </Text>
              </Text>
            </NavbarTitleContainer>
            <NavbarLinksContainer>
              <NavbarLinksContainer2>
                <SlicedButton>index</SlicedButton>
                <SlicedButton>about</SlicedButton>
              </NavbarLinksContainer2>
            </NavbarLinksContainer>

          </NavigationBar>
          {/* <BorderContainer>
            <ThemeToggle />
            <Text>Test</Text>
            <Text>
              Get started by editing&nbsp;
              <code>pages/index.tsx</code>
            </Text>

            <TextLabel>
              <Text size={8} weight={2}>
                {'FULL STACK '}
                <Text size={8} weight={1} >DEVELOPER</Text>
              </Text>
            </TextLabel>

            <Text>github</Text>

          </BorderContainer> */}
        </Wrapper>
      </main>
    </>
  )
}

const Wrapper = styled('div', {
  display: 'flex',
  flexDirection: 'column',
  margin: '25px',
});

const NavbarTitleContainer = styled('div', {
  display: 'flex',
  flexDirection: 'column',
});

const NavbarLinksContainer = styled('div', {
  // position:  'relative',
  // bottom: 0,
});

const NavbarLinksContainer2 = styled('div', {
  paddingTop: '23px',
  display: 'flex',
  flexDirection: 'row',
  // justifyContent: 'flex-end',
  // alignItems: 'flex-end',
  // gap: '10px'
});

const NavigationBar = styled('div', {
  height: '50px',
  background: 'rgba(50, 82, 97, .25)',
  display: 'flex',
  // borderRadius: '3px',
  flexDirection: 'row',
  alignItems: 'center',
  gap: '12px',
});
