import Head from 'next/head'
import ThemeToggle from '../modules/index/ThemeToggle'
import { SlicedButton, Text } from '../components/ThemedElements';
import TextLabel from '@/components/TextLabel';
import { styled } from 'stitches.config';
import Image from 'next/image'
import BorderContainer from '@/components/BorderContainer';
import DottedTopBorderBox from '@/components/DottedTopBorderBox';

export default function Home() {
  return (
    <>
      <Head>
        <title>x7ci - index</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Wrapper>

          <NavigationBar>
            <Image
              src="/react_hexagon.png"
              alt="Picture of the author"
              width={44}
              height={46}
            />
            <NavbarTitleContainer>
              <Text color="yellow" size={7} weight={2}>
                {'FULL STACK '}
                <Text size={7} weight={1} >DEVELOPER</Text>
              </Text>
              <Text color="cyan" size={1} weight={2}>
                {'SEQUENCE: '}
                <Text color="cyanLight" size={1} weight={2}>
                  {'771-C/3309-M2'}
                </Text>
              </Text>
            </NavbarTitleContainer>
            <div style={{ width: 16 }} />
            <NavbarLinksContainer>
              <NavbarLinksContainer2>
                <SlicedButton>index</SlicedButton>
                <SlicedButton>about</SlicedButton>
                <ThemeToggle />
              </NavbarLinksContainer2>
            </NavbarLinksContainer>
          </NavigationBar>

          <div style={{ height: 30 }} />

          <DottedTopBorderBox withHorizontalLine>
            <div style={{ height: 14 }} />
            This is a test container.
            <div>
              This is a test container.
            </div>
            This is a test container.
          </DottedTopBorderBox>
          {/* <BorderContainer>
            <ThemeToggle />
            <Text>Test</Text>
            <Text>
            Get started by editing&nbsp;
            <code>pages/index.tsx</code>
            </Text>
            
            <TextLabel>
              <Text size={8} weight={2}>
              {'FULL STACK '}
              <Text size={8} weight={1} >DEVELOPER</Text>
              </Text>
              </TextLabel>

              <Text>github</Text>
              
            </BorderContainer> */}
        </Wrapper>
      </main>
    </>
  )
}

const Wrapper = styled('div', {
  display: 'flex',
  flexDirection: 'column',
  margin: '$sizes$tileSize',
});

const NavbarTitleContainer = styled('div', {
  display: 'flex',
  flexDirection: 'column',
});

const NavbarLinksContainer = styled('div', {
  display: 'flex',
  flexDirection: 'column',
  justifyContent: 'flex-end',
  height: '$sizes$navigationBarHeight',
});

const NavbarLinksContainer2 = styled('div', {
  // paddingTop: '23px',
  display: 'flex',
  flexDirection: 'row',
  // justifyContent: 'flex-end',
  // alignItems: 'flex-end',
  // gap: '4px'
});

const NavigationBar = styled('div', {
  height: '$sizes$navigationBarHeight',
  paddingLeft: '12px',
  background: 'rgba(50, 82, 97, .25)',
  display: 'flex',
  // borderRadius: '3px',
  flexDirection: 'row',
  alignItems: 'center',
  gap: '14px',
});
